name: Workflow DevSecOps
run-name: Tentative de DevSecOps à but pédagogique
on: [push]
jobs:
  DAST:
    runs-on: ubuntu:latest
    steps: 
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://apzero.bts-sio-eiffel.fr'
